# Generated by Django 3.0.8 on 2020-07-23 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200722_2309'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '削除')], default=1, verbose_name='状態')),
                ('is_nav', models.BooleanField(default=False, verbose_name='ナビに表示するか')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='追加時間')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='タグ名')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '削除')], default=1, verbose_name='状態')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='追加時間')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='品名')),
                ('desc', models.CharField(blank=True, max_length=1024, verbose_name='紹介')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '削除'), (2, '編集中')], default=1, verbose_name='ステータス')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='追加時間')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodss.Category', verbose_name='分類')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('tag', models.ManyToManyField(null=True, to='goodss.Tag', verbose_name='タグ')),
                ('user_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Group')),
            ],
            options={
                'verbose_name': '貸出品',
                'verbose_name_plural': '貸出品',
                'ordering': ['-id'],
            },
        ),
    ]
