# Generated by Django 3.0.8 on 2020-07-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='tag',
            field=models.ManyToManyField(to='goodss.Tag', verbose_name='タグ'),
        ),
    ]
