# Generated by Django 3.0.8 on 2020-07-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodss', '0002_auto_20200723_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='goods/'),
        ),
    ]
