# Generated by Django 3.0.8 on 2020-07-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodss', '0006_auto_20200728_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='カテゴリー名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='品名'),
        ),
    ]
