# Generated by Django 3.0.8 on 2020-07-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200722_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='グループ内のスタッフなのか'),
        ),
    ]
