# Generated by Django 3.0.8 on 2020-07-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.IntegerField(null=True, verbose_name='追加者'),
        ),
    ]
