# Generated by Django 3.0.8 on 2020-07-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_group_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.CharField(max_length=100, null=True, verbose_name='追加者'),
        ),
    ]
