# Generated by Django 3.0.8 on 2020-07-25 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodss', '0005_auto_20200725_2152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=1, verbose_name='貸出数')),
                ('status', models.PositiveIntegerField(choices=[(1, 'チェックイン'), (0, '未チェックイン'), (2, '返却完了')], default=0, verbose_name='状態')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='コメント')),
                ('plans_return_time', models.DateTimeField(verbose_name='予定返却時間')),
                ('returned_time', models.DateTimeField(null=True, verbose_name='実際返却時間')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='追加時間')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodss.Goods', verbose_name='貸出品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '貸出スケジュール',
                'verbose_name_plural': '貸出スケジュール',
                'unique_together': {('user', 'goods')},
            },
        ),
    ]
